name: Run

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: [0 1000,1000 2000,2000 3000,3000 4000,4000 5000,5000 6000,6000 7000,7000 8000,8000 9000,9000 10000,10000 11000,11000 12000,12000 13000,13000 14000,14000 15000,15000 16000,16000 17000,17000 18000,18000 19000,19000 20000,20000 21000,21000 22000,22000 23000,23000 24000,24000 25000,25000 25800]
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install seleniumbase==4.27.0
          python -m pip install supabase
          sudo apt install -y google-chrome-stable
          seleniumbase install chromedriver
          sudo apt install -y xvfb
          export DISPLAY=:0
          /usr/bin/Xvfb :0 -screen 0 1024x768x24 &
          sleep 5
          xvfb-run python run-t.py ${{matrix.RangeIndex}}
      - name: done
        run: exit
